# NLP Practice (Text Prep)

In [1]:
import pandas as pd
import numpy as np

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
    self.io_loop.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\lenovo\AppData\Local\Temp\ipykernel_6616\2162656668.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
    self.io_loop.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\lenovo\AppData\Local\Temp\ipykernel_6616\2162656668.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
    self.io_loop.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\lenovo\AppData\Local\Temp\ipykernel_6616\2162656668.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\lenovo\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
    self.io_loop.start()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\lenovo\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\lenovo\AppData\Local\Temp\ipykernel_6616\2162656668.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\lenovo\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
import random

# Sample text patterns with noise
texts = [
    "Hey!!! Are you coming to the party tonight?? 😄",
    "BREAKING NEWS: Something unbelievable just happened...",
    "Well... I guess it's okay? Not great, not terrible.",
    "Order now!!! Save 50%!!! Only for today!!! $$$",
    "I can't believe it... she said 'yes'! <3",
    "Visit our site at www.example.com!!! #BestDeals",
    "Hmm... maybe I'll go, maybe I won't. Who knows?",
    "This is CRAZY!!! Unbelievable!!! 😱🔥",
    "Just chillin', doin' nothing... kinda bored, tbh.",
    "Sooo tired... need ☕ and a good nap – ASAP!"
]

labels = [
    'invitation', 'news', 'neutral', 'advertisement', 'romantic',
    'promotion', 'confused', 'excited', 'bored', 'tired'
]

# List of sample movie names (at least 100)
movie_names = [
    "The Shawshank Redemption", "The Godfather", "The Dark Knight", "Pulp Fiction",
    "The Lord of the Rings", "Forrest Gump", "Inception", "Fight Club", "The Matrix", 
    "Goodfellas", "Se7en", "Interstellar", "The Silence of the Lambs", "The Green Mile", 
    "Saving Private Ryan", "Parasite", "Gladiator", "The Lion King", "Whiplash", 
    "The Prestige", "Joker", "Titanic", "The Departed", "The Pianist", "Braveheart", 
    "Schindler's List", "Django Unchained", "Avengers: Endgame", "The Wolf of Wall Street",
    "Shutter Island", "1917", "The Social Network", "La La Land", "The Revenant", 
    "Black Panther", "The Imitation Game", "A Beautiful Mind", "The Grand Budapest Hotel",
    "Toy Story", "Coco", "Up", "Inside Out", "Finding Nemo", "WALL·E", "Monsters, Inc.",
    "The Incredibles", "Ratatouille", "Frozen", "Moana", "Zootopia", "Big Hero 6", 
    "Soul", "Luca", "Turning Red", "Encanto", "Lightyear", "Onward", "Frozen II", 
    "Cars", "Cars 2", "Cars 3", "Toy Story 2", "Toy Story 3", "Toy Story 4", 
    "Thor: Ragnarok", "Iron Man", "Iron Man 2", "Iron Man 3", "Captain America: The Winter Soldier",
    "Captain America: Civil War", "Doctor Strange", "Ant-Man", "Ant-Man and the Wasp", 
    "Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Spider-Man: Homecoming", 
    "Spider-Man: Far From Home", "Spider-Man: No Way Home", "No Time to Die", 
    "Skyfall", "Casino Royale", "Spectre", "Quantum of Solace", "The Batman", 
    "The Flash", "Aquaman", "Wonder Woman", "Man of Steel", "Justice League", 
    "Tenet", "Oppenheimer", "Barbie", "Napoleon", "Mission: Impossible – Fallout", 
    "Top Gun: Maverick", "John Wick", "John Wick: Chapter 2", "John Wick: Chapter 3", 
    "John Wick: Chapter 4", "The Hunger Games", "Catching Fire", "Mockingjay Part 1", 
    "Mockingjay Part 2", "Dune", "Dune: Part Two"
]

# Shuffle and pick first 100 movie names
random.shuffle(movie_names)
movie_column = movie_names[:100]

data = {
    'id': list(range(1, 101)),
    'text': [random.choice(texts) for _ in range(100)],
    'label': [random.choice(labels) for _ in range(100)]
}

df_large = pd.DataFrame(data)

# Replace 'id' with 'movie'
df_large['movie'] = movie_column
df_large = df_large[['movie', 'text', 'label']]  # Reorder columns

df_large.head()

,movie,text,label
0,The Lion King,I can't believe it... she said 'yes'! <3,promotion
1,John Wick: Chapter 2,I can't believe it... she said 'yes'! <3,neutral
2,Quantum of Solace,BREAKING NEWS: Something unbelievable just hap...,news
3,Black Panther,Order now!!! Save 50%!!! Only for today!!! $$$,advertisement
4,Whiplash,"Hmm... maybe I'll go, maybe I won't. Who knows?",promotion

In [3]:
df = df_large

In [4]:
df.sample(10)

,movie,text,label
76,The Prestige,Visit our site at www.example.com!!! #BestDeals,invitation
14,The Incredibles,"Hmm... maybe I'll go, maybe I won't. Who knows?",romantic
79,Encanto,Sooo tired... need ☕ and a good nap – ASAP!,confused
82,Iron Man,"Just chillin', doin' nothing... kinda bored, tbh.",confused
48,Goodfellas,Hey!!! Are you coming to the party tonight?? 😄,tired
41,Inception,Visit our site at www.example.com!!! #BestDeals,bored
73,Cars 2,This is CRAZY!!! Unbelievable!!! 😱🔥,tired
59,Fight Club,Sooo tired... need ☕ and a good nap – ASAP!,confused
51,The Dark Knight,Order now!!! Save 50%!!! Only for today!!! $$$,promotion
13,Turning Red,"Just chillin', doin' nothing... kinda bored, tbh.",confused

## LowerCase

In [5]:
df['movie'] = df['movie'].str.lower()

In [6]:
df

,movie,text,label
0,the lion king,I can't believe it... she said 'yes'! <3,promotion
1,john wick: chapter 2,I can't believe it... she said 'yes'! <3,neutral
2,quantum of solace,BREAKING NEWS: Something unbelievable just hap...,news
3,black panther,Order now!!! Save 50%!!! Only for today!!! $$$,advertisement
4,whiplash,"Hmm... maybe I'll go, maybe I won't. Who knows?",promotion
...,...,...,...
95,ant-man,I can't believe it... she said 'yes'! <3,invitation
96,coco,"Well... I guess it's okay? Not great, not terr...",excited
97,forrest gump,Visit our site at www.example.com!!! #BestDeals,neutral
98,spider-man: homecoming,"Hmm... maybe I'll go, maybe I won't. Who knows?",news
99,mission: impossible – fallout,Hey!!! Are you coming to the party tonight?? 😄,advertisement

In [7]:
df = df.apply(lambda x: x.str.lower() if x.dtype == "object" else x)

In [8]:
df

,movie,text,label
0,the lion king,i can't believe it... she said 'yes'! <3,promotion
1,john wick: chapter 2,i can't believe it... she said 'yes'! <3,neutral
2,quantum of solace,breaking news: something unbelievable just hap...,news
3,black panther,order now!!! save 50%!!! only for today!!! $$$,advertisement
4,whiplash,"hmm... maybe i'll go, maybe i won't. who knows?",promotion
...,...,...,...
95,ant-man,i can't believe it... she said 'yes'! <3,invitation
96,coco,"well... i guess it's okay? not great, not terr...",excited
97,forrest gump,visit our site at www.example.com!!! #bestdeals,neutral
98,spider-man: homecoming,"hmm... maybe i'll go, maybe i won't. who knows?",news
99,mission: impossible – fallout,hey!!! are you coming to the party tonight?? 😄,advertisement

## Remove Html tags and URLs in the text

In [9]:
import re

text = "Welcome to <b>my website</b>!"
cleaned = re.sub(r'<[^>]+>', '', text)
print(cleaned)

Welcome to my website!

In [10]:
def remove_html(text):
    return re.sub(r'<[^>]+>', '', text)

def remove_urls(text):
    return re.sub(r'http[s]?://\S+|www\.\S+', '', text)

def clean_text(text):
    if isinstance(text, str):
        text = remove_html(text)
        text = remove_urls(text)
    return text

In [11]:
df = df.applymap(clean_text)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_6616\2197956661.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(clean_text)

In [12]:
df['text'][88]

"well... i guess it's okay? not great, not terrible."

## Remove Punctuation

In [13]:
import string
exclude = string.punctuation

In [14]:
def remove_punctuation(text):
    # Create a translation table that maps each punctuation character to None
    translator = str.maketrans('', '', exclude)
    return text.translate(translator)

In [15]:
df = df.applymap(remove_punctuation)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_6616\1414281388.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(remove_punctuation)

In [16]:
df['text'][35]

'this is crazy unbelievable 😱🔥'

In [17]:
df

,movie,text,label
0,the lion king,i cant believe it she said yes 3,promotion
1,john wick chapter 2,i cant believe it she said yes 3,neutral
2,quantum of solace,breaking news something unbelievable just happ...,news
3,black panther,order now save 50 only for today,advertisement
4,whiplash,hmm maybe ill go maybe i wont who knows,promotion
...,...,...,...
95,antman,i cant believe it she said yes 3,invitation
96,coco,well i guess its okay not great not terrible,excited
97,forrest gump,visit our site at bestdeals,neutral
98,spiderman homecoming,hmm maybe ill go maybe i wont who knows,news
99,mission impossible – fallout,hey are you coming to the party tonight 😄,advertisement

## Spelling Correction

In [18]:
# pip install textblob

In [19]:
from textblob import TextBlob

def correct_spelling(text):
    # Create a TextBlob object
    blob = TextBlob(text)
    return str(blob.correct())

In [20]:
df = df.map(correct_spelling)

## Remove Stopwords

In [21]:
# pip install nltk

In [22]:
import nltk
from nltk.corpus import stopwords

# Download the list of stopwords
nltk.download('stopwords')

# Get English stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    # Split text into words
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
df = df.map(remove_stopwords)

In [24]:
df.sample(10)

             movie                                           text       label
95          animal                             believe said yes 3  invitation
43            done                            order save 50 today     neutral
97     forest jump                           visit site bestdeals     neutral
65         lighter                     hey coming party tonight 😄     neutral
93            cars               soon tired need ☕ good nap – sap  invitation
37  doctor strange               soon tired need ☕ good nap – sap     excited
85  social network               soon tired need ☕ good nap – sap  invitation
91       godfather                 well guess okay great terrible        news
38            soul                            order save 50 today     neutral
74            tent  breaking news something unbelievable happened   promotion

In [25]:
df['text'][43]

'order save 50 today'

## Deal With Emojis

In [26]:
# pip install emoji

In [27]:
import emoji

def replace_emojis_with_text(text):
    return emoji.demojize(text)

In [28]:
df = df.map(replace_emojis_with_text)

In [29]:
df.sample(10)

,movie,text,label
26,guardians galaxy vol 2,soon tired need :hot_beverage: good nap – sap,promotion
58,mockingly part 2,breaking news something unbelievable happened,bored
71,iron man 2,well guess okay great terrible,neutral
49,iron man 3,well guess okay great terrible,bored
40,john wick chapter 4,soon tired need :hot_beverage: good nap – sap,advertisement
39,gladiator,hey coming party tonight :grinning_face_with_s...,confused
14,incredible,maybe ill go maybe wont knows,romantic
84,toy story 2,visit site bestdeals,bored
79,enfants,soon tired need :hot_beverage: good nap – sap,confused
50,man steel,hey coming party tonight :grinning_face_with_s...,romantic

In [30]:
df['text'][13]

'chill nothing kind bored th'

## Tokenization

In [31]:
# pip install spacy;

In [32]:
# pip show spacy

In [33]:
# !python -m spacy download en_core_web_sm

In [34]:
import spacy

# Load the English language model
nlp = spacy.load('en_core_web_sm')

In [35]:
def spacy_tokenization(text):
    # Process the text through spaCy pipeline
    doc = nlp(text)
    # Extract tokens from the processed document (doc)
    return [token.text for token in doc]

In [36]:
df['token'] = df['text'].apply(spacy_tokenization)

In [37]:
df

,movie,text,label,token
0,lion king,believe said yes 3,promotion,"[believe, said, yes, 3]"
1,john wick chapter 2,believe said yes 3,neutral,"[believe, said, yes, 3]"
2,quantum solace,breaking news something unbelievable happened,news,"[breaking, news, something, unbelievable, happ..."
3,black another,order save 50 today,advertisement,"[order, save, 50, today]"
4,whiplash,maybe ill go maybe wont knows,promotion,"[maybe, ill, go, maybe, wo, nt, knows]"
...,...,...,...,...
95,animal,believe said yes 3,invitation,"[believe, said, yes, 3]"
96,cock,well guess okay great terrible,excited,"[well, guess, okay, great, terrible]"
97,forest jump,visit site bestdeals,neutral,"[visit, site, bestdeals]"
98,spiderman homecoming,maybe ill go maybe wont knows,news,"[maybe, ill, go, maybe, wo, nt, knows]"
99,mission impossible – ballot,hey coming party tonight :grinning_face_with_s...,advertisement,"[hey, coming, party, tonight, :, grinning_face..."

## Stemming

In [38]:
from nltk.stem import PorterStemmer

In [41]:
stm = PorterStemmer()

def apply_stemming(tokens):

    return [stm.stem(token) for token in tokens]

In [42]:
df['token'] = df['token'].apply(apply_stemming)

In [43]:
df

,movie,text,label,token
0,lion king,believe said yes 3,promotion,"[believ, said, ye, 3]"
1,john wick chapter 2,believe said yes 3,neutral,"[believ, said, ye, 3]"
2,quantum solace,breaking news something unbelievable happened,news,"[break, news, someth, unbeliev, happen]"
3,black another,order save 50 today,advertisement,"[order, save, 50, today]"
4,whiplash,maybe ill go maybe wont knows,promotion,"[mayb, ill, go, mayb, wo, nt, know]"
...,...,...,...,...
95,animal,believe said yes 3,invitation,"[believ, said, ye, 3]"
96,cock,well guess okay great terrible,excited,"[well, guess, okay, great, terribl]"
97,forest jump,visit site bestdeals,neutral,"[visit, site, bestdeal]"
98,spiderman homecoming,maybe ill go maybe wont knows,news,"[mayb, ill, go, mayb, wo, nt, know]"
99,mission impossible – ballot,hey coming party tonight :grinning_face_with_s...,advertisement,"[hey, come, parti, tonight, :, grinning_face_w..."